### ISSUE TITLE
Requires babel-plugin-transform-class-properties

### ISSUE THREAD

**Issue by almeynman** [Jam3/react-background-video-player#2]
The way the methods are written requires babel transformation, which is not a part of es6.

I would rather use a built component (with plain js) or change arrow function methods to normal methods, supported by es6

I am happy to submit a PR with the changes if you are fine with that.

**Comment by seleckis** [comment]
It seems it was fixed, isn't it?

**Comment by namniak** [comment]
Sorry, yes. The latest version is transpiled. 
Thanks for opening the issue.
