### ISSUE TITLE
Why don't you use `poster` attr instead of div with background?

### ISSUE THREAD

**Issue by seleckis** [Jam3/react-background-video-player#7]
This is standard attribute: https://developer.mozilla.org/en/docs/Web/HTML/Element/video

**Comment by namniak** [comment]
The reason is you can show this poster with any start time, unlike actual video poster. Say you start the video at 20 seconds, and you still can have poster if the user didn't start playing. So instead of being dependent on progress (currentTime = 0) it's based on "has started"

**Comment by seleckis** [comment]
Ok, I've got
