### ISSUE TITLE
shouldComponentUpdate? [question]

### ISSUE THREAD

**Issue by tspringborg** [Jam3/react-background-video-player#9]
Getting this warning.
`Warning: BackgroundVideo has a method called shouldComponentUpdate(). shouldComponentUpdate should not be used when extending React.PureComponent. Please extend React.Component if shouldComponentUpdate is used.`

in index.js
```
...
class BackgroundVideo extends PureComponent {
...
shouldComponentUpdate(nextState, nextProps) {
    return this.props.shouldComponentUpdate;
  }
```
Why not extend React.Component instead?

**Comment by namniak** [comment]
Updated
